# Generated by Django 4.2.3 on 2023-07-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_processedvideo_rawvideo_delete_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedVideo",
        ),
        migrations.DeleteModel(
            name="RawVideo",
        ),
    ]
