# Generated by Django 4.2.3 on 2023-07-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedVideo",
        ),
    ]
