# Generated by Django 4.2.3 on 2023-07-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedVideo",
        ),
    ]
