# Generated by Django 4.2.3 on 2023-08-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedVideo",
        ),
    ]
