# Generated by Django 4.2.3 on 2023-09-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedVideo",
        ),
    ]
