# Generated by Django 4.2.3 on 2023-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedvideo",
            name="video_description",
            field=models.CharField(max_length=2000),
        ),
    ]
