# Generated by Django 3.2.8 on 2024-02-14 21:52

from django.db import migrations
import uuid

def assign_uuids(apps,schema_editor):
    ProcessedVideo = apps.get_model("base", "ProcessedVideo")
    for video in ProcessedVideo.object.filter(hashId__isnull=True):
        video.hashId = uuid.uuid4()
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_processedvideo_video_description'),
    ]

    operations = [
        migrations.RunPython(assign_uuids)
    ]
