# Generated by Django 3.2.8 on 2024-02-14 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20240214_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedvideo',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
