# Generated by Django 3.2.8 on 2024-02-14 22:02

from django.db import migrations
import uuid

def reassign_hash_id(apps, schema_editor):
    ProcessedVideo = apps.get_model("base", "ProcessedVideo")
    for vid in ProcessedVideo.objects.all():
        vid.hash_id = uuid.uuid4()
        vid.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_processedvideo_hash_id'),
    ]

    operations = [
        migrations.RunPython(reassign_hash_id)
    ]
