# Generated by Django 3.2.8 on 2024-02-14 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20240214_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedvideo',
            name='id',
        ),
        migrations.AlterField(
            model_name='processedvideo',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
